#!/bin/bash -u

PROXY_PORT="$1"
DASHBOARD_URL="http://localhost:${PROXY_PORT}/ui"

_retry() {
  [ -z "${2}" ] && return 1
  echo -n ${1}
  until printf "." && "${@:2}" &>/dev/null; do sleep 1.2; done; echo "✓"
}

case "${OSTYPE}" in
 linux*)
    OPEN="xdg-open"
    ;;
 darwin*)
    OPEN="open"
    ;;
esac

command -v ${OPEN} &> /dev/null
[ $? -ne 0 ] && ( echo "cannot determine 'open' command" ; exit 1 )

kubectl cluster-info &> /dev/null
[ $? -ne 0 ] && ( echo "cluster is not healthy" ; exit 1 )

kubectl proxy --port=${PROXY_PORT} &
echo "✓ kubectl proxy is listening"
_retry "❤ Waiting for local proxy to become online" curl -sSf "${DASHBOARD_URL}"

${OPEN} ${DASHBOARD_URL}

