#!/bin/bash -eu

OUTDIR="$1"
INTERNAL_TLD="$2"
CLUSTER_DOMAIN="$3"
DNS_SERVICE_IP="$4"

echo "❤ Patching addon scripts "

[ -d ${OUTDIR} ] || mkdir -p ${OUTDIR}
cp manifests/addons/* ${OUTDIR}

sed -i.bak 's|${CLUSTER_DOMAIN}|'"${CLUSTER_DOMAIN}|g" "${OUTDIR}/"*.tpl
sed -i.bak 's|${DNS_SERVICE_IP}|'"${DNS_SERVICE_IP}|g" "${OUTDIR}/"*.tpl
sed -i.bak 's|${INTERNAL_TLD}|'"${INTERNAL_TLD}|g" "${OUTDIR}/"*.tpl

for file in ${OUTDIR}/*.tpl
  do mv "${file}" ${file/.tpl/}
done

rm -f ${OUTDIR}/*.bak

echo "✓ Patching add-on scripts success"

# ✗
