#!/bin/bash -eux


TFSTATE="$1"
[ -z "$TFSTATE" ] && echo "Require TFSTATE as first parameter"
CMD_TFOUTPUT='terraform output -state="${TFSTATE}"'

BASTION_IP=$(${CMD_TFOUTPUT} bastion-ip)
INTERNAL_TLD=$(${CMD_TFOUTPUT} internal-tld)
ETCD_URL="http://etcd.${INTERNAL_TLD}:2379"

SSH_CMD="ssh -A core@${BASTION_IP}"

${SSH_CMD} -- curl -s ${ETCD_URL}/version | grep '{"etcdserver":"2.3.2","etcdcluster":"2.3.0"}'
${SSH_CMD} -- curl -s ${ETCD_URL}/health | grep true
${SSH_CMD} -- curl -s ${ETCD_URL}/v2/members | grep -o 'name' | wc -l | grep 4
