#!/bin/bash -eu

EXTERNAL_ELB="$1"

_retry() {
  [ -z "${2}" ] && return 1
  echo -n ${1}
  until printf "." && "${@:2}" &>/dev/null; do sleep 5.2; done; echo "✓"
}

echo "❤ Polling for cluster life - this could take a minute or more"

_retry "❤ Waiting for DNS to resolve for ${EXTERNAL_ELB}" ping -c1 "${EXTERNAL_ELB}"
_retry "❤ Curling apiserver external elb" curl --insecure --silent "https://${EXTERNAL_ELB}"
_retry "❤ Trying to connect to cluster with kubectl" kubectl cluster-info

kubectl cluster-info
